[package]
name = "example"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
# https://github.com/starkware-libs/starknet-staking
# https://github.com/WaterCoolerStudiosInc/starknet-staking
[dependencies]

starknet = "2.9.2"

#contracts_commons = { git = "https://github.com/starkware-libs/starknet-staking" }
openzeppelin = "0.20.0"


[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.34.0" }
staking = { git = "https://github.com/starkware-libs/starknet-staking" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
